### ISSUE TITLE
Avoid using eval

### ISSUE THREAD

**Issue by hkupty** [miorimmax/cq#1]
It can be potentially dangerous (such as running a command that removes your data).
https://github.com/miorimmax/cq/blob/master/cq.clj#L10
Ask @giovanifss about that :)

**Comment by miorimmax** [comment]
That's a good point but I put it there intentionally to allow the use of Clojure code directly, rather than inventing a new syntax (kinda like how jq does). 🤔

**Comment by hkupty** [comment]
That makes sense, but a DSL would allow you to drop the `#(-> %)` in favor of a more natural syntax.
But feel free to close the issue, I'm just picking on you..
